module common;

public static const float EDGE_SOFTNESS = 2;
public static const float PI = 3.14159265359;

public struct Global {
  public float2 viewport;
  public float2 bg_size;
  public float3 bg_color;
  public float3 bd_color;
  public float3 minimap_circ;
  public float2 view;
  public float2 lview;
  public float zoom;
  public float bg_opacity;
  public float bg_scale;
  public float bd_opacity;
  public float bd_radius; 
  public float grd;
  public float max_minimap_size;
  public float minimap_data_size;
  public float minimap_opacity;
}
